MODEL:
  BACKBONE:
    NAME: 'build_resnet_fpn_backbone'
  WEIGHTS: "./R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100 #20
    NUM_CLASSES: 80
DATASETS:
  # TRAIN: ("voc_2007_train",)
  # TEST:  ("voc_2007_val",)
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 5
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
