_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "./R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 80
DATASETS:
  # TRAIN: ("voc_2007_train",)
  # TEST:  ("voc_2007_val",)
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (46000, 50000)
  MAX_ITER: 54000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
